### ISSUE TITLE
Breaking change from NUnit 2.x -> 3.x regarding setting of appbase

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit-project-loader#13] opened 2017-10-23 11:50 UTC
@Fernell commented on [Sat Jul 29 2017](https://github.com/nunit/nunit-console/issues/273#issuecomment-318828860)

I migrated from nunit 2.x to 3.7.1 and it seems that something changed in the way that tests are loading from nunit project file. After I debug nunit-console myself I found out in InnerException message that my real error was "Could not load file or assembly nunit.framework". Having this error I was able to google how to fix it. I needed to add "appbase" attribute to nunit project with proper path to nunit.framework.dll.
So maybe it is not bug in nunit console but in project loader extension?

---

@ChrisMaddock commented on [Sat Jul 29 2017](https://github.com/nunit/nunit-console/issues/273#issuecomment-318862166)

@CharliePoole - Do you know if there was any intentional breaking changes here, from v2-> v3?

@Fernell - can you share you NUnit project file, so we can see why the defaults didn't work for you?

---

@CharliePoole commented on [Sun Jul 30 2017](https://github.com/nunit/nunit-console/issues/273#issuecomment-318884177)

The main difference is that the old console actually loaded the assembly, which requires all references to be present. That automatically gave a clearer error message. In NUnit 3, we examine the references in the test assembly without loading, so any failure occurs a bit later, in the driver, when we actually load it.

What has not changed, at least, intentionally, is how we set the appbase by default when a project is used. That's the potential bug here, along with a better error message.

---

@Fernell commented on [Mon Jul 31 2017](https://github.com/nunit/nunit-console/issues/273#issuecomment-319040256)

My old nunit file looked like this:

```
<NUnitProject>
    <Config name="Debug" binpath="." runtimeFramework="net-4.5">
        <assembly path="BuildOutput\Debug\someTest1.dll" />
        <assembly path="BuildOutput\Debug\someTest2.dll" />
        <assembly path="BuildOutput\Debug\someTest3.dll" />
    </Config>
</NUnitProject>
```

I needed to change it to this:

```
<NUnitProject>
    <Config name="Debug" binpath="." appbase="BuildOutput\Debug\" runtimeFramework="net-4.5">
        <assembly path="someTest1.dll" />
        <assembly path="someTest2.dll" />
        <assembly path="someTest3.dll" />
    </Config>
</NUnitProject>
```

**Comment by ChrisMaddock** [comment] 2017-10-23 11:52
To be investigated, as to whether there's a bug here, and whether we should fix it.

**Comment by CharliePoole** [comment] 2021-08-30 02:49
I reviewed this very old bug and ran some tests. The use of `bindir="."` confused the issue somewhat. This should never be used because it's telling NUnit that the user is taking responsibility for locating all dependencies by providing a path manually. Using "." is especially problematic because it indicates that all dependencies will be found in the current directory, i.e. the directory from which the user ran the console program. It's hard to think of a case where all the dependencies would be found there!

Normally, bindir is not specified and NUnit figures it out automatically.

Appbase, on the other hand is usually required because it tells the user where the test assemblies are located. If not provided, they are assumed to be in the same directory as the nunit project file, which would be unusual.

Unfortunately, we don't have much information from this old report as to the relative location of the project file and the assemblies, which is the most critical aspect of it.

I'm going to close this as not a bug but I will merge in some changes I made to make it easier to debug the problem.

**Closed as completed** 2021-08-30 05:09 UTC
Labels: Not a Bug

**Comment by Fernell** [comment] 2021-08-30 08:41
![5l9ila](https://user-images.githubusercontent.com/6044248/131311858-1d010fa8-78ac-43c0-b1d1-2e8131efab60.jpg)

**Comment by CharliePoole** [comment] 2021-08-30 11:37
Sorry about that, @Fernell. I've been away from this project for a few years, and I'm trying to clean up all old issues now. We should have asked more questions about what you were doing back in 2017!

**Comment by Fernell** [comment] 2021-08-30 11:50
No worries. I was just surprised seeing this old bug dug up all of the sudden :) Also I cannot give you any more info about it because I no longer have access to the source codes. Oh well. Good luck with cleaning the issues.
